name: Setup Go Environment
description: Install X11 dependencies and setup Go

inputs:
  go-version:
    description: Go version to install
    required: false
    default: stable

runs:
  using: composite
  steps:
    - name: Install X11 dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y libx11-dev

    - name: Setup Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version: ${{ inputs.go-version }}
        cache: true
