name: Setup Go Environment
description: Checkout code, install X11 dependencies, and setup Go

inputs:
  go-version:
    description: Go version to install
    required: false
    default: stable

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Install X11 dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y libx11-dev

    - name: Setup Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
      with:
        go-version: ${{ inputs.go-version }}
        cache: true
