version: "2"

linters:
  enable:
    # Defaults
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    # Additional
    - gosec
    - bidichk
    - errorlint
    - bodyclose
    - unconvert
    - usestdlibvars
    - modernize
    - exhaustive
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
          - unused
  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
    errcheck:
      check-type-assertions: true
      check-blank: true
    unused:
      parameters-are-used: false
    exhaustive:
      default-signifies-exhaustive: true
    gosec:
      excludes:
        - G304

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/osamingo/go-csvpp

run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
